In [1]:
import numpy as np
import os
import pandas as pd
home_path = os.path.expanduser("~") + '/'
from utils.load_data import *
from utils.info_params import *

OpenCV is built with OpenMP support. This usually results in poor performance. For details, see https://github.com/tensorpack/benchmarks/blob/master/ImageNet/benchmark-opencv-resize.py


In [2]:
train_data_file_name = home_path + "data/ccxt/preprocessing_data/BTC_USDT_binance_1h.csv_train"
test_data_file_name = home_path + "data/ccxt/preprocessing_data/BTC_USDT_binance_1h.csv_test"
normalize_data = 'min-max'
normalize_data_idx = True

In [3]:
df_train = pd.read_csv(train_data_file_name)
df_train

Timestamp     Open     High      Low    Close       Volume  \
0      2017-08-22 08:00:00  3798.08  3805.76  3750.08  3794.12    36.868111   
1      2017-08-22 09:00:00  3794.12  3920.31  3775.01  3904.56    76.172178   
2      2017-08-22 10:00:00  3904.56  3904.56  3826.12  3844.08    59.322181   
3      2017-08-22 11:00:00  3844.07  3905.56  3841.18  3866.48    49.368766   
4      2017-08-22 12:00:00  3866.48  3990.12  3853.53  3934.01    75.787584   
5      2017-08-22 13:00:00  3949.01  3964.75  3874.35  3920.99    38.623871   
6      2017-08-22 14:00:00  3874.38  3920.99  3786.81  3849.00    26.182528   
7      2017-08-22 15:00:00  3829.50  3921.63  3810.07  3858.23    38.764438   
8      2017-08-22 16:00:00  3858.23  3952.89  3853.47  3905.84    34.779778   
9      2017-08-22 17:00:00  3905.84  3998.99  3888.79  3943.00    45.279128   
10     2017-08-22 18:00:00  3944.00  4104.82  3944.00  4043.76    45.132143   
11     2017-08-22 19:00:00  4071.22  4101.24  3984.23  3984.24    34.344606   
12     2017-08-22 20:00:00  3984.50  4061.54  3953.13  3960.29    30.512424   
13     2017-08-22 21:00:00  3960.29  4038.96  3946.67  3946.67    21.285573   
14     2017-08-22 22:00:00  3999.96  4046.11  3944.04  4002.00    31.264903   
15     2017-08-22 23:00:00  4009.10  4045.00  3944.03  4040.00    41.089781   
16     2017-08-23 00:00:00  4040.00  4077.18  4013.89  4036.00    23.850037   
17     2017-08-23 01:00:00  4048.10  4100.00  4035.38  4100.00    46.576410   
18     2017-08-23 02:00:00  4101.53  4127.99  4049.74  4083.72    45.835226   
19     2017-08-23 03:00:00  4083.72  4126.99  4050.04  4100.41    43.396711   
20     2017-08-23 04:00:00  4084.54  4115.87  4054.01  4083.60    37.869418   
21     2017-08-23 05:00:00  4084.00  4110.00  4053.18  4053.18    32.819431   
22     2017-08-23 06:00:00  4064.00  4099.99  4035.32  4080.00    35.942493   
23     2017-08-23 07:00:00  4089.45  4098.88  4052.49  4074.88    35.208261   
24     2017-08-23 08:00:00  4081.63  4124.00  4057.00  4124.00    37.697918   
25     2017-08-23 09:00:00  4123.88  4242.32  4100.15  4203.12    40.181197   
26     2017-08-23 10:00:00  4208.11  4228.02  4188.63  4228.02    24.062874   
27     2017-08-23 11:00:00  4203.12  4237.99  4174.09  4237.99    33.082033   
28     2017-08-23 12:00:00  4205.98  4265.80  4174.00  4215.68    62.638690   
29     2017-08-23 13:00:00  4215.68  4230.92  4155.00  4211.00    81.248254   
...                    ...      ...      ...      ...      ...          ...   
17617  2019-08-30 18:00:00  9523.45  9547.99  9486.55  9509.75   793.640800   
17618  2019-08-30 19:00:00  9509.75  9592.00  9450.35  9571.66  1510.654787   
17619  2019-08-30 20:00:00  9572.13  9696.00  9572.13  9621.40  2203.011699   
17620  2019-08-30 21:00:00  9621.40  9625.00  9578.17  9584.25   529.622729   
17621  2019-08-30 22:00:00  9584.96  9612.59  9567.09  9594.57   548.961203   
17622  2019-08-30 23:00:00  9594.57  9638.00  9555.00  9584.54   706.206383   
17623  2019-08-31 00:00:00  9582.76  9614.29  9566.42  9597.43   631.888996   
17624  2019-08-31 01:00:00  9597.53  9652.00  9590.60  9626.08  1199.214689   
17625  2019-08-31 02:00:00  9625.05  9655.77  9610.00  9621.02   464.931598   
17626  2019-08-31 03:00:00  9620.97  9639.54  9601.65  9611.26   353.968949   
17627  2019-08-31 04:00:00  9611.02  9624.21  9585.01  9614.04   441.276670   
17628  2019-08-31 05:00:00  9612.88  9625.00  9594.03  9616.59   369.532476   
17629  2019-08-31 06:00:00  9616.62  9618.58  9580.32  9589.84   406.021045   
17630  2019-08-31 07:00:00  9588.03  9615.00  9576.71  9591.58   400.829487   
17631  2019-08-31 08:00:00  9588.25  9591.60  9541.00  9556.00   838.039965   
17632  2019-08-31 09:00:00  9557.00  9583.23  9520.58  9568.84   895.722675   
17633  2019-08-31 10:00:00  9568.84  9588.67  9554.04  9571.13   384.193887   
17634  2019-08-31 11:00:00  9571.48  9575.00  9535.43  9553.85   502.143637   
17635  2019-08-31 12:00:00  9553.22  9604.06  9545.61  9591.30   66

In [4]:
df_test = pd.read_csv(test_data_file_name)
df_test

Timestamp     Open     High      Low    Close       Volume  \
0    2019-09-01 00:00:00  9588.74  9630.00  9579.34  9617.06   546.960415   
1    2019-09-01 01:00:00  9617.06  9642.58  9612.08  9614.99   453.105152   
2    2019-09-01 02:00:00  9614.99  9616.00  9595.76  9605.78   458.004517   
3    2019-09-01 03:00:00  9606.12  9624.01  9605.78  9623.02   633.588749   
4    2019-09-01 04:00:00  9623.02  9630.21  9605.60  9614.46   542.260896   
5    2019-09-01 05:00:00  9616.12  9618.25  9598.46  9602.25   196.759259   
6    2019-09-01 06:00:00  9602.25  9615.44  9595.87  9611.84   215.983606   
7    2019-09-01 07:00:00  9612.50  9619.37  9604.30  9608.10   272.364879   
8    2019-09-01 08:00:00  9608.06  9610.19  9550.00  9590.72   968.941892   
9    2019-09-01 09:00:00  9590.57  9609.00  9560.15  9591.37   840.349506   
10   2019-09-01 10:00:00  9591.54  9595.00  9567.74  9580.66   406.627872   
11   2019-09-01 11:00:00  9582.23  9589.11  9567.73  9571.05   312.838996   
12   2019-09-01 12:00:00  9571.99  9584.99  9561.53  9577.31   456.875422   
13   2019-09-01 13:00:00  9577.82  9583.01  9545.46  9567.99   592.971475   
14   2019-09-01 14:00:00  9568.77  9581.00  9558.26  9576.86   342.640312   
15   2019-09-01 15:00:00  9575.00  9659.00  9561.06  9604.26  1245.840598   
16   2019-09-01 16:00:00  9601.38  9614.34  9555.00  9575.38   885.448135   
17   2019-09-01 17:00:00  9575.01  9630.00  9520.00  9586.52   958.852469   
18   2019-09-01 18:00:00  9586.52  9616.84  9581.96  9599.98   548.183612   
19   2019-09-01 19:00:00  9599.98  9632.00  9577.17  9616.96   646.754124   
20   2019-09-01 20:00:00  9615.30  9627.87  9597.89  9618.45   375.218327   
21   2019-09-01 21:00:00  9621.97  9779.00  9615.45  9682.55  2614.177507   
22   2019-09-01 22:00:00  9680.05  9830.00  9680.05  9773.63  2021.041628   
23   2019-09-01 23:00:00  9774.98  9795.58  9708.15  9724.98  3009.615495   
24   2019-09-02 00:00:00  9723.59  9756.34  9712.50  9742.36  3571.926755   
25   2019-09-02 01:00:00  9742.36  9754.82  9735.00  9737.56   650.161875   
26   2019-09-02 02:00:00  9739.02  9793.00  9735.00  9764.04   838.239467   
27   2019-09-02 03:00:00  9764.80  9775.00  9736.00  9743.16   693.622952   
28   2019-09-02 04:00:00  9741.76  9773.06  9738.68  9765.95   756.930930   
29   2019-09-02 05:00:00  9768.40  9775.00  9748.00  9749.00   436.187528   
..                   ...      ...      ...      ...      ...          ...   
690  2019-09-29 18:00:00  7991.92  8018.01  7955.00  7981.66   775.732728   
691  2019-09-29 19:00:00  7981.66  8008.15  7917.84  7950.69  1666.734935   
692  2019-09-29 20:00:00  7953.09  8004.00  7918.98  7990.00  1123.806597   
693  2019-09-29 21:00:00  7990.00  8099.00  7970.00  8039.86  2222.884097   
694  2019-09-29 22:00:00  8039.86  8131.03  8019.09  8074.67  1700.795617   
695  2019-09-29 23:00:00  8074.07  8096.01  8038.48  8043.82   634.993021   
696  2019-09-30 00:00:00  8043.04  8056.55  7970.00  8008.59   948.328423   
697  2019-09-30 01:00:00  8006.77  8024.13  7963.86  8022.03  1190.780058   
698  2019-09-30 02:00:00  8022.03  8023.42  7966.30  7986.06  1270.065934   
699  2019-09-30 03:00:00  7984.63  7991.52  7955.00  7972.13   879.059959   
700  2019-09-30 04:00:00  7972.11  7975.00  7710.00  7822.83  7417.656578   
701  2019-09-30 05:00:00  7822.83  7862.74  7765.50  7799.62  2500.435204   
702  2019-09-30 06:00:00  7798.92  7819.00  7733.00  7754.54  2251.059248   
703  2019-09-30 07:00:00  7754.50  7823.94  7740.00  7794.42  1706.079585   
704  2019-09-30 08:00:00  7794.74  7900.00  7775.02  7866.92  2416.830370   
705  2019-09-30 09:00:00  7867.39  8040.00  7842.00  8002.64  3756.082127   
706  2019-09-30 10:00:00  8003.52  8088.00  7986.14  8042.09  3191.274183   
707  2019-09-30 11:00:00  8042.21  8099.00  8010.80  8031.30  2246.119151   
708  2019-09-30 12:00:00  8033.33  8056.47  7982.56  7998.49  1458.759797   
709  2019-09-30 13:00:00  7997.94  8152.80  7997.91  8114.76  4459.172673   
710  2019-0

In [5]:
df_train.columns

Index(['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume', 'N_buy',
       'N_sell', 'buy_amount_avg', 'sell_amount_avg', 'buy_amount_std',
       'sell_amount_std', 'price_avg', 'price_std', 'cost_avg', 'cost_std',
       'Unix_timestamp', 'Spread_Open_Close', 'Spread_High_Low',
       'Spread_Buy_Sell', 'Spread_Buy_Sell_avg', 'MA_Close_3', 'MA_Close_12',
       'MA_Close_24', 'MA_Close_120', '_1d_Open', '_1d_High', '_1d_Low',
       '_1d_Close', '_1d_Volume', '_1d_N_buy', '_1d_N_sell',
       '_1d_buy_amount_avg', '_1d_sell_amount_avg', '_1d_buy_amount_std',
       '_1d_sell_amount_std', '_1d_price_avg', '_1d_price_std', '_1d_cost_avg',
       '_1d_cost_std', '_1d_Spread_Open_Close', '_1d_Spread_High_Low',
       '_1d_Spread_Buy_Sell', '_1d_Spread_Buy_Sell_avg', '_1d_MA_Close_3',
       '_1d_MA_Close_12', '_1d_MA_Close_24', '_1d_MA_Close_120', '1d_target',
       'trend'],
      dtype='object')

In [6]:
cols = [
       'Open', 'High', 'Low', 'Close', 'Volume', 'N_buy',
       'N_sell', 'buy_amount_avg', 'sell_amount_avg', 'buy_amount_std',
       'sell_amount_std', 'price_avg', 'price_std', 'cost_avg', 'cost_std',
       'Spread_Open_Close', 'Spread_High_Low', 'Spread_Buy_Sell', 'Spread_Buy_Sell_avg',
       'MA_Close_3', 'MA_Close_12', 'MA_Close_24', 'MA_Close_120',
       '_1d_Open', '_1d_High', '_1d_Low', '_1d_Close', '_1d_Volume', '_1d_N_buy', '_1d_N_sell',
       '_1d_buy_amount_avg', '_1d_sell_amount_avg', '_1d_buy_amount_std',
       '_1d_sell_amount_std', '_1d_price_avg', '_1d_price_std', '_1d_cost_avg',
       '_1d_cost_std', '_1d_Spread_Open_Close', '_1d_Spread_High_Low',
       '_1d_Spread_Buy_Sell', '_1d_Spread_Buy_Sell_avg',
       '_1d_MA_Close_3', '_1d_MA_Close_12', '_1d_MA_Close_24', '_1d_MA_Close_120',
]

In [7]:
N_val = 3 * 30 * 24 # 3 month = 2160 hours
N_val

2160

In [8]:
X = df_train[cols].values
y = df_train['trend'].values


X_train = X[:-N_val]
y_train = y[:-N_val]
X_val = X[-N_val:]
y_val = y[-N_val:]

X_test = df_test[cols].values
y_test = df_test['trend'].values


In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

In [10]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C = 0.1)
clf.fit(X_train, y_train)

/home/nam/miniconda3/envs/python3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score

y_train_hat = clf.predict(X_train)
cm = confusion_matrix(y_train, y_train_hat)
rp = classification_report(y_train, y_train_hat)
score = accuracy_score(y_train, y_train_hat)
f1 = f1_score(y_train, y_train_hat)

print(cm)
print(rp)
print(score)
print('f1_score : ', f1)

[[2384 5085]
 [1932 6086]]
              precision    recall  f1-score   support

           0       0.55      0.32      0.40      7469
           1       0.54      0.76      0.63      8018

   micro avg       0.55      0.55      0.55     15487
   macro avg       0.55      0.54      0.52     15487
weighted avg       0.55      0.55      0.52     15487

0.5469103118744754
f1_score :  0.6343217468341237


In [12]:
y_pred = clf.predict(X_val)
cm = confusion_matrix(y_val, y_pred)
rp = classification_report(y_val, y_pred)
score = accuracy_score(y_val, y_pred)
f1 = f1_score(y_val, y_pred)

print(cm)
print(rp)
print(score)
print('f1_score : ', f1)

[[715 334]
 [621 490]]
              precision    recall  f1-score   support

           0       0.54      0.68      0.60      1049
           1       0.59      0.44      0.51      1111

   micro avg       0.56      0.56      0.56      2160
   macro avg       0.56      0.56      0.55      2160
weighted avg       0.57      0.56      0.55      2160

0.5578703703703703
f1_score :  0.5064599483204134


# Test metrics

In [13]:
y_pred = clf.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
rp = classification_report(y_test, y_pred)
score = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(cm)
print(rp)
print(score)
print('f1_score : ', f1)

[[266 107]
 [218 129]]
              precision    recall  f1-score   support

           0       0.55      0.71      0.62       373
           1       0.55      0.37      0.44       347

   micro avg       0.55      0.55      0.55       720
   macro avg       0.55      0.54      0.53       720
weighted avg       0.55      0.55      0.53       720

0.5486111111111112
f1_score :  0.44253859348198976
